### ISSUE TITLE
Error executing the instruction

### ISSUE THREAD

**Issue by tutlo-kirov** [alt-cloud/getaltcos#30]
При выполнении инструкции 
https://github.com/alt-cloud/getaltcos/blob/feature-fromACOStoALTCOS/docs/make_iso.md
на этапе сборки архива altcos.tar
gleb@core-i5 altcos_build $ make -C mkimage-profiles DEBUG=1 APTCONF=$PWD/apt/apt.conf.sisyphus.x86_64 IMAGEDIR=$PWD/out vm/altcos.tar
make: вход в каталог «/home/gleb/Общедоступные/Make_ISO/altcos_build/mkimage-profiles»
** goal: vm/altcos.tar
** ARCH: x86_64
make[1]: *** Нет правила для сборки цели «vm/altcos.tar».  Останов.
make: *** [Makefile:42: vm/altcos.tar] Ошибка 1
make: выход из каталога «/home/gleb/Общедоступные/Make_ISO/altcos_build/mkimage-profiles»

**Comment by keremet** [comment]
Исправлено тут http://git.altlinux.org/people/keremet/packages/?p=mkimage-profiles.git;a=commit;h=592e0863c1bbc1cc84dcd25d61b9038abd2c1b34
